FROM python:3.10-slim

WORKDIR /app

# Install system dependencies for Postgres driver
RUN apt-get update && apt-get install -y libpq-dev gcc

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

# No EXPOSE needed because this is a background worker
CMD ["python", "main.py"]