# Stage 1: Build the Go Binary
FROM golang:1.21-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o main .

# Stage 2: Run the Binary (Tiny Image)
FROM alpine:latest
WORKDIR /root/
COPY --from=builder /app/main .
EXPOSE 3080
CMD ["./main"]